### ISSUE TITLE
Add custom properties to schema

### ISSUE THREAD

**Issue by stasovlas** [seriousme/fastify-openapi-glue#128]
In function ```makeSchema``` I found that ```tags, summary, description, operationId``` properties are adding in schema, so I think whould be very useful to add custom properties (which starts with ```x-```)  in schema too.

**Comment by seriousme** [comment]
Currently the `tags, summary, description, operationId` properties don't alter the behaviour of fastify. I just added them to the parser in case the generator would need them.

Do you have any example in which you would use this ?

Kind regards,
Hans

**Comment by stasovlas** [comment]
For example, in [schema](https://github.com/ringcentral/ringcentral-api-specifications/blob/master/ringcentral.spec.2019110220191017-1140.openapi3.yaml) at first path ```/restapi``` we have property ```x-auth-required```, so in fastify hook ```preHandler``` I can do auth or not depends this property

**Comment by seriousme** [comment]
Well I think adding the `x-` attributes would not help there because the security handlers only look at the `security` property at top level or at operation/path level. Even if the parser would copy the `x-` attributes then the security handlers would not know about them and as the `x-` properties are non-standard by default there is no standard way to tell the security handlers how to deal with them.

If you own the schema then you could use the standard OpenAPI way of specifying [security requirements](http://spec.openapis.org/oas/v3.0.3#security-requirement-object), if not then you either need to write a transformation for the schema (either by hand or by writing some code) or you need to add a pre-handler to fastify yourself and tell it what to do on which paths.

Kind regards,
Hans

**Comment by stasovlas** [comment]
```x-auth-required``` - just an example. It can be any property with any logic. Another example, ```x-log-kibana``` for logging request body in kibana.

**Comment by seriousme** [comment]
If we copy that to the schema, how can you then access this in any prehandler ?
`fastify-openapi-glue` only uses prehandlers for securityHandling.

Do you have some example application code that would be able to utilize this schema if we would add those `x-` fields ?

**Comment by seriousme** [comment]
Even better would be a test case that currently fails but would succeed once an  `x-` field is added ;-)

**Comment by stasovlas** [comment]
schema:

```
paths:
  /restapi:
    get:
      tags:
        - API Info
      summary: Get API Versions
      description: Returns current API version(s) and server info.
      operationId: readAPIVersions
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetVersionsResponse"
      x-log-kibana: true
```

code:

```
app.addHook('preHandler', async (request, reply) => {
  if (reply.context.schema['x-log-kibana']) {
    logKibana(request.params);
  }
});
```

**Comment by seriousme** [comment]
Ok, I learned something new today, thanks for that :-)
I did't know that the schema was present in the reply context.

**Comment by seriousme** [comment]
Published as v2.2.0 on npm

Kind regards,
Hans

**Comment by stasovlas** [comment]
Thank you! But can you add this feature to v1?

**Comment by seriousme** [comment]
Technically that is doable, but I'm not sure how to do that without keeping v1 alive for a longer time and I'm not keen on maintaining multiple versions (security updates etc).

I guess you want it back ported because of fastify 2.x vs 3.x  as that is the difference between fastify-openapi-glue 1.x and 2.x.
The breaking change is https://github.com/seriousme/fastify-openapi-glue/pull/92

If you have an idea by which I can help you out without maintaining multiple code bases then I am open to suggestions :-)

Kind regards,
Hans

**Comment by stasovlas** [comment]
If it causes problems then don't do it.
Thank you for feature!
