### ISSUE TITLE
Only last schema is used for endpoints with multiple mimetypes

### ISSUE THREAD

**Issue by artu-ole** [seriousme/fastify-openapi-glue#174]
Only last schema is being used for endpoints with multiple mimetypes:
https://github.com/seriousme/fastify-openapi-glue/blob/a0269cfd605796baaf0d510b94e281b610346e75/lib/parser.v3.js#L71-L80

which contradicts the spec stating that [Schemas can vary by media type.](https://swagger.io/docs/specification/describing-request-body/)

Therefore, following sample spec will not consume `text/plain` requests by throwing
```
{
    "statusCode": 400,
    "error": "Bad Request",
    "message": "body should be object"
}
```

<details>
<summary>Sample spec:</summary>

```yaml
openapi: 3.0.0
info:
  version: 1.0.0
  title: Test
paths:
  "/test":
    post:
      summary: Multiple mimetypes payload
      operationId: test
      requestBody:
        content:
          text/plain:
            schema:
              type: string
          application/json:
            schema:
              $ref: "#/components/schemas/TestMessage"
      responses:
        "200":
          description: Message received
components:
  schemas:
    TestMessage:
      type: object
      nullable: true
      properties:
        id:
          type: number
          description: Id
```
</details>

**Comment by seriousme** [comment]
Hi, 

Thanks for submitting this issue.  You are correct that the spec says that schemas can vary by media type.
Unfortunately there seems to be no way to explain this to fastify :-(

fastify only allows for one schema per route: 
https://www.fastify.io/docs/latest/Routes/#options

An alternative might be to define separate routes, one for text/plain and one for application/json.

Please be aware that fastify does parse nor validate text/plain
https://github.com/fastify/fastify/issues/2686

Does this answer your question ?

Kind regards,
Hans

**Comment by artu-ole** [comment]
Hey, thanks for a prompt reply!

I believe fastify does validate body for `text/plain`. In the ticket you have linked there was a missing type in the schema and a precaution that fastify does not parse the body to json object, leaving it as string, which is fair.

It is not possible to specify schema per mediatype as far as I can see, however, it is possible to combine multiple schemas on the fly since JSON Schema supports keyword nesting.
Here's the naive approach:
```js
  parseBody(data) {
    let schema;
    if (data && data.content) {
      schema = {
        oneOf: []
      }
      for (const mimeType in data.content) {
        this.config.contentTypes.add(mimeType);
        schema.oneOf.push(data.content[mimeType].schema);
      }
    }
    return schema;
  }
```

<details>
<summary>Sample spec</summary>

```yaml
openapi: 3.0.0
info:
  version: 1.0.0
  title: Test
paths:
  "/test":
    post:
      summary: Multiple mimetypes payload
      operationId: test
      requestBody:
        content:
          text/plain:
            schema:
              type: string
          application/json:
            schema:
              anyOf:
                - type: object
                  required:
                    - customProperty1
                  properties:
                    customProperty1:
                      type: string
                      description: customProperty1
                - type: object
                  required:
                    - customProperty2
                  properties:
                    customProperty2:
                      type: number
                      description: customProperty2
      responses:
        "200":
          description: Message received
```
</details>

Then fastify which will accept a string for `text/plain` and correctly validate objects for `application/json`. Let me know if I've overlooked something!

**Comment by seriousme** [comment]
Hi,

I have to say it's a creative solution !

First thing that came to mind was: can you have a oneOf with only one item.
I checked the [JSON meta schema for applicator](https://json-schema.org/draft/2019-09/meta/applicator) and having a `oneOf` with a single item is allowed, so that was good news :-)

Second question I had was: did you try it out and did it work ?
(e.g. if you add the oneOf to the schema, does the string validation work and when the string validation fails, do you still get the "body should be object" error ?

Automagically merging the two schemas is a bit of a risk. E.g. any string matching your pattern is now also accepted for application/json.

In your case its acceptable to have the merger because you ran into the issue. But for others it might lead to unpredictable behavior. E.g. the above error because the string validation failed .

I think we have a few options:
1. let the user fix the schema. Either by using an editor, or by having some code that fixes it before its fed to fastify-openapi-glue
2. put schema merging behind a flag so the user needs to make a conscious decision and accept the weird error
3. ask the fastify crew for a solution and piggyback on that once it is available.

As you might guess my preference is with option 3 as that would solve it in the most clean way. 

What do you think ?

Kind regards,
Hans

**Comment by artu-ole** [comment]
> Second question I had was: did you try it out and did it work ?

Yes, in case string is submitted to `application/json` and validation fails the error message contains all of the permutations, e.g. for the spec from previous comment:
```js
{
  statusCode: 400,
  error: "Bad Request",
  message: "body should match pattern \"^1$\", body should be object, body should be object, body should match some schema in anyOf, body should match exactly one schema in oneOf",
}
```

It does indeed bring potentially harmful behavior of accepting string for `application/json` due to fastify's shortcoming of not allowing schemas per mediatype like we discussed above. 

I have to agree that first two solutions, although tempting, would somewhat bloat the plug and play nature of library and this issue falls more under `Known limitations` in my opinion until there is a sensible upstream configuration flexibility.

I can work around the issue in multiple ways in the mean time, be it [custom mediatype parser](https://www.fastify.io/docs/latest/ContentTypeParser/), another endpoint or restricting the api to a single mediatype, so it's in no way a blocker and all good with me!

**Comment by seriousme** [comment]
I have just added a [note](https://github.com/seriousme/fastify-openapi-glue#notes) to the README to clarify the topic.

Thanks for the input.

Kind regards,
Hans

**Comment by artu-ole** [comment]
Thank you for the quick turnaround and support on the matter! I consider this case closed at the time.
