### ISSUE TITLE
Support security schemas

### ISSUE THREAD

**Issue by delfrrr** [seriousme/fastify-openapi-glue#43]
given this openapi

```
openapi: "3.0.0"
info:
  title: API
  version: 1.0.0
paths:
  /:
    get:
      operationId: getVersion
      summary: Show API Version
      parameters:
        - name: authorization
          in: header
          schema:
            type: string
          required: true
      security:
        - FirebaseToken: []
components:
  securitySchemes:
    FirebaseToken:
      type: http
      scheme: bearer
      bearerFormat: bearer
```

I expect that user cannot access endpoint without providing `authorization` header

**Comment by seriousme** [comment]
I just added a test for a missing `authorization` header (see #44 ) and that returns a '500' if you don't provide an authorization header. So without providing at least some data in the header the user cannot access the endpoint.

That does **not** mean that the authorization data provided itself is valid !!
You will still need to check the validity of the authorization data in your code.

Does this answer your question ?

Kind regards,
Hans

**Comment by delfrrr** [comment]
oh sorry, my mistake: I was plying around with a schema and forgot to delete parameters description. The schema should look like this:

```
openapi: "3.0.0"
info:
  title: API
  version: 1.0.0
paths:
  /:
    get:
      operationId: getVersion
      summary: Show API Version
      security:
        - FirebaseToken: []
components:
  securitySchemes:
    FirebaseToken:
      type: http
      scheme: bearer
      bearerFormat: bearer
```

so I expect 40x in this case;

if course if I additionally provide

```
      parameters:
        - name: authorization
          in: header
          schema:
            type: string
          required: true
```

then it kinda works

**Comment by seriousme** [comment]
Ah, I see your point !

The problem is that fastify itself does not have a standard mechanism for all possible [security scheme variants](https://swagger.io/docs/specification/authentication/). Therefore there is no reliable way to automatically convert security schemes into fastify configuration :-(

So the only options for you for now are:
- chain another plug-in which takes care of bearer authorization for you
- check the bearer header on every operation being called and return a 404 if non is present.

Kind regards,
Hans

**Comment by seriousme** [comment]
Btw:  I have added a notes section to the README.md to clarify this behaviour.
Thanks for pointing this out.

**Comment by seriousme** [comment]
Can we close this issue ?
