### ISSUE TITLE
Support for union types in schema?

### ISSUE THREAD

**Issue by JulianCataldo** [seriousme/fastify-openapi-glue#445]
Hey there!

Where using union types somewhere in a schema like this:

```json
"type": ["string", "null"]
```

```sh
# CLI
openapi-glue <options…>
```

Yields:

```json
  {
    "instancePath": "/components/schemas/User/properties/name/type",
    "schemaPath": "#/properties/type/type",
    "keyword": "type",
    "params": {
      "type": "string"
    },
    "message": "must be string"
  },
  {
    "instancePath": "/components/schemas/User/properties/name",
    "schemaPath": "#/definitions/Reference/required",
    "keyword": "required",
    "params": {
      "missingProperty": "$ref"
    },
    "message": "must have required property '$ref'"
  },
```

No generation.

Replace with:

```json
"type": "string"
```

=> No errors, generation is done.

Is this specific to my schemas (made with [prisma-json-schema-generator](https://www.npmjs.com/package/prisma-json-schema-generator)) or the underlying AJV Options / JSON Schema version under the hood?

Thanks

**Comment by seriousme** [comment]
Hi,

thanks for asking.
I think the problem lies in the generated schema as AJV does support JSON schema 07 by default and fastify-openapi-glue relies on the version of AJV built into Fastify.

I did a small test myself and the `"type": ["string", "null"]` does not work with the AJV configuration in Fastify.
AJV itself can handle union types (https://ajv.js.org/strict-mode.html#strict-types)
The workaround seems to be to explicitly specify:

```json
{
  "anyOf": [
    {
      "type": "string"
    },
    {
      "type": "null"
    },
  ]
}
```
as mentioned on the AJV page.

Hope this helps!

Kind regards,
Hans
