### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module

### ISSUE THREAD

**Issue by jedaan** [seriousme/fastify-openapi-glue#453]
Hi , 
i am using fastify with typescript 
getting the below error 

 Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: ....\node_modules\fastify-openapi-glue\index.js
[App] require() of ES modules is not supported.
[App] require() of....\node_modules\fastify-openapi-glue\index.js from C:\ppf\yettel-auth\dist\app.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.

my tsconfig 
{
  "extends": "fastify-tsconfig",
  "compilerOptions": {
    "outDir": "dist",
    "sourceMap": true
  },
  "include": ["src/**/*.ts", "src/routes/customers/schema.ts"]
}

**Comment by mhamann** [comment]
I have this same problem. Using typescript, it converts this:

```
const fastifyOpenApiGlue = await import('fastify-openapi-glue');
```

into this:

```
const fastifyOpenApiGlue = await Promise.resolve().then(() => __importStar(require('fastify-openapi-glue')));
```

**Comment by seriousme** [comment]
Hi Matt,

The trick seems to be to prevent Typescript from converting back to commonJS.
Did you see: https://github.com/seriousme/fastify-openapi-glue/issues/427 ?

If that does not resolve it can you please share your tsconfig.json ?

Kind regards,
Hans

**Comment by mhamann** [comment]
In looking at #427, it seems that part of the solution is setting `type: module` in `package.json`. We have a blend of TS and JS files in our package, so converting to a pure module would be a huge lift.

This is our current tsconfig:

```
{
  "compilerOptions": {
    "target": "es2017",                                  

    "experimentalDecorators": true,                   
    "emitDecoratorMetadata": true,                    

    "module": "commonjs",                                
    "rootDir": "./src",                                  
    "resolveJsonModule": true,                        
    "allowJs": true,                                  
    "sourceMap": true,                                
    "outDir": "./build",                                   
    "esModuleInterop": true,                             
    "forceConsistentCasingInFileNames": true,            
    "strict": true,                                      
    "skipLibCheck": true                                 
  },
  "include": [
    "./**/*",
    "src/**/*.json"
  ],
  "exclude": [
      "./test/**/*",
      "./build/**/*",
      "./*.js",
      "node_modules"
  ]
}
```

**Comment by seriousme** [comment]
Looking at: https://2ality.com/2021/06/typescript-esm-nodejs.html you might want to set:

```
"module": "ES2020", // (A)
"moduleResolution": "Node", // (B) 
"allowSyntheticDefaultImports": true, // (C)
```

- Line A (["module"](https://www.typescriptlang.org/tsconfig#module)): We are telling TypeScript to generate ECMAScript modules.
  - "ES6", "ES2015": support for basi- "ES6", "ES2015": support for basic ESM features
  - "2020": additionally, support for dynamic imports and import.meta.
- Line B (["moduleResolution"](https://www.typescriptlang.org/tsconfig#moduleResolution)): This value is needed for Node.js.
- Line C (["allowSyntheticDefaultImports"](https://www.typescriptlang.org/tsconfig#allowSyntheticDefaultImports)): I needed this setting in order to import a legacy CommonJS module. The module.exports were the default export in that case.

Hope this helps!
