### ISSUE TITLE
using "example" in swagger api

### ISSUE THREAD

**Issue by shayff** [seriousme/fastify-openapi-glue#495]
Hello,

In a swagger 2.0 JSON API definition I have the following schema definitions:

```
{
  "info": {
    "title": "title",
    "version": "1"
  },
  "swagger": "2.0",
  "paths": {
    "/api/v1/user/{userId}/something": {
      "post": {
        "tags": [
          "something"
        ],
        "description": "Do something",
        "parameters": [
          {
            "in": "path",
            "name": "userId",
            "type": "string",
            "required": true,
            "description": "The user id"
          }
        ],
        "responses": {
          "200": {
            "description": "Did something",
            "schema": {
              "type": "string",
              "example": "Done"
            }
          },
          "404": {
            "description": "Didnt do something",
            "schema": {
              "type": "string",
              "example": "Failed"
            }
          }
        }
      }
    }
  },
  "definitions": {},
  "responses": {},
  "tags": []
}
```

While using glue i'm getting the following error:
`Error while starting the application: Error: Could not initiate module due to error: FastifyError: Failed building the validation schema for POST: /api/v1/user/{userId}/something, due to error strict mode: unknown keyword: "example"`

I checked at https://editor.swagger.io/ and using "example" seems valid, any idea why?

**Comment by seriousme** [comment]
Hi,

thanks for asking !
The `example` field is valid in a Swagger spec, but not in JSONschema and that is what Fastify uses to validate the config.
The resolution is simple: tell Fastify not to use `strict mode` by passing an option.

E.g. if you use "fastify start":

https://github.com/seriousme/fastify-openapi-glue/blob/5b2c18bd3abf24855b3101c7aa69192464ed6c67/examples/petstore/index.js#L19-L25

If you run fastify directtly from your code then this should work:  

```javascript
const fastify = require('fastify')({
       ajv: {
		customOptions: {
			strict: false,
		},
	},
};
```
https://fastify.dev/docs/latest/Reference/Server#factory-ajv

Hope this helps !

Kind regards,
Hans

**Comment by shayff** [comment]
It worked!
But I'm still don't understand why fastify fail that if I use "example", they don't support swagger API?
Thank you for your details response!

**Comment by seriousme** [comment]
Hi,

good to read it worked.
The challenge is that:
```json
            "schema": {
              "type": "string",
              "example": "Failed"
```

Is valid Swagger, but not valid [JSONschema](https://json-schema.org/)  
Fastify knows about JSONschema, but not about Swagger.

Fastify-openapi-glue converts the contents of the Swagger specification to configuration for Swagger, including the route schema's. Unfortunately this does not always match as you found out. In that case the work around is to either strip the extra attributes from the specification or to tell Fastify to be less strict.

I added a note to [README.md](https://github.com/seriousme/fastify-openapi-glue/blob/master/README.md#notes) to explain this better. So your question helped me improve the documentation ;-)

KInd regards,
Hans

**Comment by shayff** [comment]
Hey,

If that is the case, shouldn't we remove the "example" as part of the converting of glue to Fastify?

Thanks

**Comment by seriousme** [comment]
Hi,

that could be an option, however schema's can be almost infinitely complex so its not as simple as: strip all object properties called "example".

E.g. this is valid Swagger and valid JSONschema:
```json
{
 "type": "object",
 "properties": {
   "example": {
     "type": "string"
   }
 }
}
```

And will match the Javascript Object:
```javascript
{ example: "hello" }
```

whereas this is valid Swagger, but not valid JSONschema:
```json
{
 "type": "object",
 "properties": {
   "example": {
     "type": "string",
     "example": "hello"
   }
 }
}
```

The  OpenAPI specification allows for a superset of JSONschema, although the use of  `example` is discouraged:
See: https://spec.openapis.org/oas/v3.1.0#schemaObject
The spec says that you can basically add anything to the schema. Which might be nice from a documentation perspective where the specification is generated from code but is quite inconvenient from a Design first perspective where code is generated from the specification.

I also looked at letting AJV do a prevalidation and then filter out the validation errors that result from that but that can become rather complex and might result in the plugin trying to fix real errors leading to unpredictable behaviour :-( 

In older versions of Fastify AJV was not using `strict mode` but since Fastify 4 it does. 
So the safest way is to let Fastifty ignore schema validation errors.

It's not ideal but in my view the least bad of all available options ;-)

KInd regards,
Hans

**Comment by seriousme** [comment]
Btw:  the best solution would of course be that the OpenAPI team would talk to the JSONschema team and align on extensions ;-)
