### ISSUE TITLE
OpenAPI 3 server url

### ISSUE THREAD

**Issue by tanvp112** [seriousme/fastify-openapi-glue#56]
Hi,

I converted the petstore-swagger.v2.json to openAPI 3 with editor.swagger.io. I noticed that v3 no longer requires basePath and it will be substitute by servers array.

"servers": [
    {
      "url": "http://petstore.swagger.io/v3"
    }
  ],

 However, when swapped with the petstore example:

const options = {
  specification: `${__dirname}/petstore-swagger.v3.json`,
  service: `${__dirname}/service.js`
};

curl -s -XGET http://localhost:3000/v3/pet/24 -H "accept: application/json" | python -m json.tool
{
    "error": "Not Found",
    "message": "Route GET:/v3/pet/24 not found",
    "statusCode": 404
}

If "v3" is removed from the server URL then it works like this, BUT notice that the photoUrl key was not returned:

curl -s -XGET http://localhost:3000/pet/24 -H "accept: application/json" | python -m json.tool
{
    "id": 24,
    "name": "Kitty the cat",
    "photoUrls": [],
    "status": "available"
}

Any idea how to retain the server url as specified in the specification and how to return correct photoUrls?

Thanks.

**Comment by seriousme** [comment]
Hi,

thanks for asking.
OpenAPI V3 has indeed removed the "baseURL" from the spec and only allows you to specify "servers". As the servers specification can contain multiple elements its hard to guess how the developer wants to expose the API. Therefore I added a prefix option (see https://github.com/seriousme/fastify-openapi-glue#options) which allows you to specify the path under which you want to expose the operations.

The photoURLs  problem is was bug in the example. Instead of returning an array of strings service.js returned an array of objects which has been fixed now (see https://github.com/seriousme/fastify-openapi-glue/commit/52a284d08598d818bd0c00a457ce5fc6716a8606). Thanks for spotting this one!

Does this answer your questions ?

**Comment by tanvp112** [comment]
The prefix key can support only one version, right?

Thanks to the update for the photoUrls return type.

**Comment by seriousme** [comment]
Correct, as you typically use one specification on one path.

However since the result produced by  is a fastify plugin there is nothing that prevents you from creating multiple plugins on multiple prefixes and loading them all up in Fastify.

e.g. something along the lines of:
```javascript
const fastify = require('fastify')()
const openapiGlue = require("fastify-openapi-glue");

const specification = `${__dirname}/petstore-swagger.v2.json`;

fastify.register(
    openapiGlue,
    {
        specification,
        service: `${__dirname}/serviceV1.js`,
        prefix: "v1"
    }
)

fastify.register(
    openapiGlue,
    {
        specification,
        service:`${__dirname}/serviceV2.js`
        prefix: "v2"
    }
)

fastify.listen(3000)
```

or if you really want to be done quickly checkout https://github.com/fastify/fastify-autoload

**Comment by tanvp112** [comment]
Awesome! your solution is really neat. With **careful** project folder structure and naming, fastify-autoload will be great.

Thanks for your prompt replies, i will go with your plugin solution.
