### ISSUE TITLE
Request : add parameter for AJV removeAdditionnal

### ISSUE THREAD

**Issue by zekth** [seriousme/fastify-openapi-glue#63]
I'm using fastify-openapi-glue on several projects and i faced an issue regarding `additionnalProperties:false`. Because of this line : https://github.com/seriousme/fastify-openapi-glue/blob/master/index.js#L53

Is it possible to add a parameter for this? This would lead in a  `HTTP 400` is there is additionnal properties.

I can write a PR for this.

**Comment by seriousme** [comment]
Hi,

technically its very easy for me to allow an extra 'ajv' option (like in [fastify](https://www.fastify.io/docs/latest/Server/#ajv)). However its a bit unclear to me what you are trying to achieve here as the openApi spec should specify the exact message formats.

Do you have an example of what triggers the error ?
Eg. a copy of a (minimal) spec file and a message that fails validation ?

Kind regards,
Hans

**Comment by zekth** [comment]
For example take this schema:
```json
{
    "type": "object",
     "additionalProperties":false,
    "properties": {
      "foo": {
        "type": "string"
      }
    }
  }
```
In the current case if we send:
```json
{
  "foo": "hello",
  "bar":"World"
}
```
This will validate but the property `bar` will be omitted. If we want to be strictly tied to the spec it would be rejected and lead to a http 400.

**Comment by seriousme** [comment]
Ok, I see the use case and I have a working prototype.
I'm going to check if I can mimick the exact behavior of the fastify ajv parameter.

Kind regards,
Hans

**Comment by seriousme** [comment]
Ok,I have been thinking about it a bit and since AJV-OAI is in the middle its a bit risky to expose the full set of AJV config so what I did is add a "noAdditional" option to the module.
(see https://github.com/seriousme/fastify-openapi-glue/tree/noAdditionalOpt#options)

The result is in :
ttps://github.com/seriousme/fastify-openapi-glue/tree/noAdditionalOpt

Does this work for you ? 
If so then I will merge with Master and publish a new version.

Kind regards,
Hans

**Comment by zekth** [comment]
Looks ok to me but i was wondering if you can get the AJV configuration of the fastify instance? I haven't dig into the code, but by this way the middleware and and the server would be on the same AJV config.

Otherwise fits the need yup. 👍

**Comment by seriousme** [comment]
The problem is are the special Open API types like int32,int64 etc. for which standard AJV has no validators :-(  Therefore I [added AJV-OAI in](https://github.com/seriousme/fastify-openapi-glue/blob/master/index.js#L50) that adds validators for those types. Downside of that is that it results in a new AJV instance and therefore I can use the fastify ajv flags.

The validators are no rocket science (see https://github.com/amazing-gao/ajv-oai/blob/master/lib/format-validator.js) .

So an alternative route would be to create an AJV plugin with for these types and use the 'ajv' option on fastify to modify the behavior of the default fastify AJV instance. This would indeed free my code from AJV config as I could leverage the config from fastify itself.

What do you think ?

Kind regards,
Hans

**Comment by zekth** [comment]
With those explanation i think the current implementation in the branch you linked is good. Anyway having both validators with `fastify` and `open-api-glue` is at the user risk to have the same behavior in a sense.

**Comment by seriousme** [comment]
I checked ajv-oai and I think it would be fairly straight forward to have it provide a AJV plugin as well so I submitted an issue  (https://github.com/amazing-gao/ajv-oai/issues/6) 

If that works out then I can simplify my code as well and can provide you (and others :-)) with transparant access to Fastify's ajv flags.

**Comment by seriousme** [comment]
I did some deeper digging and it turns out a fastify plugin can't access the AJV object of the Fastify instance :-(
(Confirmed by Matteo Colina on Gitter)

Therefore plugins always need to create a new AJV object if they want to alter AJV's behavior.
So the AJV plugin route is a dead end.

**Comment by seriousme** [comment]
New version merged and published (see https://www.npmjs.com/package/fastify-openapi-glue)

Enjoy,
Hans

**Comment by zekth** [comment]
Many thanks!
